name: 'PlayEveryWare/action-get-unity-version'
description: 'Gets the Unity version of a project'

inputs:
  path:
    description: Starting path to search for a Unity project
    default: .
    required: false
  project-version:
    description: Optional path to ProjectVersion.txt (usually not needed)
    default: ''
    required: false

outputs:
  version:
    description: Version of the Unity project
  project-path:
    description: Path to the Unity project

runs:
  using: node16
  main: dist/index.js
  post: dist/index.js
