name: test

on: workflow_dispatch

env:
  PROJECT_REPOSITORY: CaelanRP/AnotherCrabsTreasure

jobs:
  test:
    runs-on: [self-hosted, sb02]
    steps:
      - uses: PlayEveryWare/action-app-installation-pat@v1
        id: app-token
        with:
          installation-id: 30363310
          private-key: ${{ secrets.PEW_BUILDER_KEY_EL9FMYV8DVTLYMLSZJZRVL569RFZWPS }}
          repositories: ${{ env.PROJECT_REPOSITORY }}

      - uses: actions/checkout@v2
        with:
          repository: ${{ env.PROJECT_REPOSITORY }}
          token: ${{ steps.app-token.outputs.token }}
          path: title

      - uses: PlayEveryWare/action-testbed@main
        id: unity-version
        with:
          path: title

      - name: Show version (${{ steps.app-token.outputs.token }})
        run: |
          echo "Found unity version ${{ steps.unity-version.outputs.version }}"
          echo "Test value: ${{ steps.unity-version.outputs.test_value }}"
